// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzmMvUktdEvlK-_6_vB_k3O6paWlznWQ',
    appId: '1:313350964672:web:0a5ba8a1d990c433cef425',
    messagingSenderId: '313350964672',
    projectId: 'studio-6116270073-a85c2',
    authDomain: 'studio-6116270073-a85c2.firebaseapp.com',
    storageBucket: 'studio-6116270073-a85c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIj0L8bIJ4NmTCqHqjyw8dIqp7q8qU5U',
    appId: '1:313350964672:ios:7d61290d3b94fcc7cef425',
    messagingSenderId: '313350964672',
    projectId: 'studio-6116270073-a85c2',
    storageBucket: 'studio-6116270073-a85c2.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8BJxv6Xx4mu9ftZRqBMMhsKk5xHKzQDQ',
    appId: '1:313350964672:android:cf86b90ff31a3331cef425',
    messagingSenderId: '313350964672',
    projectId: 'studio-6116270073-a85c2',
    storageBucket: 'studio-6116270073-a85c2.firebasestorage.app',
  );

}